* Instalación EW Testing Framework

Repositorio con la información necesaria para puesta en marcha de LAVA. Pricipalmente se realiza el seguimiento
sobre de los ficheros de configuración de LAVA.
Cuando hablemos de artefactos se hace referencia a los ficheros anteriores.

Buscamos poder replicar lava en otras máquinas de acuerdo a nuestras especificaciones. 

A lo largo del proyecto, principalmente para familiarizarme con LAVA, he realizado dos tipos de instalación:
- La instalación simplista, poco real y para nada aconsejable en producción. Instalar todo en una misma máquina.
- La instalación actual, que ira evolucionado hasta convertise en una final y estable. Un maestro y uno o varios esclavos.

** Instalaciones 

Todas las instalaciones parte de la siguiente premisa : 

#+BEGIN_SRC
Haber instalado LAVA siguiendo las instrucciones de oficiales. Las instrucciones oficiales se pueden
consultar en la https://lkft.validation.linaro.org/static/docs/v2/pipeline-server.html. 
#+END_SRC

La documentación oficial esta muy bien detallada.


*** Simplista

La rama por_defecto contiene los artefactos de una instancia de LAVA. El maestro y esclavo en un mismo host.
El nombre del host, como de costumbre, es localhost y su dirección 127.0.0.1.

Los artefactos son 
- lava-worker o fichero de configuración del esclavo.
- lava-server-gunicorn o fichero de configuración del backend.
- lava-scheduler o fichero de configuración del planificador.
- lava-publisher o fichero de configuración del publicador de eventos.
- lava-server.conf o fichero de configuracion de proxy-reverse apache.

** Scripts
Tenemos unos scripts que nos van construir el layout del repositorio a partir de la instalación por defecto de LAVA,
es decir todos los componentes en una misma máquina.
Adicionalmente se definen unas variables y funciones de ambiente para tener un acceso directo a los fichero de configuración
y a la gestion de los servicios : parar y arrancar.
*** TODO Listado de variables 
*** TODO Listado de funciones


